name:UpdateREADMEwithRecentActivity

on:
schedule:
-cron:'0*/6***'#Rodaacada6horas
workflow_dispatch:

jobs:
update-readme:
runs-on:ubuntu-latest

steps:
-name:Checkout
uses:actions/checkout@v4

-name:UpdateREADMEwithrecentactivity
uses:jamesgeorge007/github-activity-readme@master
env:
GITHUB_TOKEN:${{secrets.GITHUB_TOKEN}}
with:
COMMIT_MSG:'Atualizaçãoautomática-Atividadesrecentes'
MAX_LINES:10
